version: '2'
services:
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
  postgres:
    image: postgres:9.3
  save4life-api:
    build: save4life-api/
    volumes: 
    - ./save4life-api/:/app
    ports:
    - "8000:80"
    depends_on:
    - postgres
    environment:
    - DATABASE_URL=postgres://save4life:password@postgres:5432/save4life
  junebug:
    image: praekeltfoundation/junebug
    environment:
    - REDIS_HOST=redis
    - AMQP_HOST=rabbitmq
    - AMQP_VHOST=/
    ports:
    - "8001:80"
    - "8080:8080"
    - "9010:9010"
    depends_on:
    - redis
    - rabbitmq
#  vumi-telnet-transport:
#    image: praekeltfoundation/vumi
#    environment:
#    - AMQP_HOST=rabbitmq
#    - WORKER_CLASS=vumi.transports.telnet.TelnetServerTransport
#    - VUMI_OPT_transport_name=telnet_transport
#    - VUMI_OPT_telnet_port=9010
#    ports:
#    - "9010:9010"
#    depends_on:
#    - rabbitmq
  vumi-jssandbox:
    build: vxsandbox/
    volumes:
    - ./app.js:/app/app.js
    - ./app-config.json:/app/config.json
    environment:
    - AMQP_HOST=rabbitmq
    - VUMI_OPT_transport_name=telnet_transport
    links:
    - save4life-api:api
    depends_on:
    - rabbitmq
    - redis
