version: '2'
services:
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
  postgres:
    image: postgres:9.3
  junebug:
    image: praekeltfoundation/junebug
    environment:
    - REDIS_HOST=redis
    - AMQP_HOST=rabbitmq
    - AMQP_VHOST=/
    ports:
    - "8001:80"
    - "8080:8080"
    - "9010:9010"
    - "9011:9011"
    depends_on:
    - redis
    - rabbitmq
  api:
    build: save4life-api/
    volumes: 
    - ./save4life-api/:/app
    ports:
    - "8000:80"
    depends_on:
    - postgres
    - rabbitmq
    - junebug
    env_file:
    - airtime_variables.env
    environment:
    - DATABASE_URL=postgres://save4life:password@postgres:5432/save4life
    - BROKER_URL=amqp://guest:guest@rabbitmq//
    - JUNEBUG_SMS_URL=http://junebug:8080/channels/202ae5bc-0be8-4390-8ab7-37fc691f4e9b/messages/
  vumi-jssandbox:
    build: save4life/
    volumes:
    - ./save4life/go-app.js:/app/app.js
    - ./app-config.json:/app/config.json
    environment:
    - AMQP_HOST=rabbitmq
    - VUMI_OPT_transport_name=telnet_transport
    depends_on:
    - rabbitmq
    - redis
    - api
