version: '2'
services:
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
  vumi-telnet-transport:
    image: praekeltfoundation/vumi
    environment:
    - AMQP_HOST=rabbitmq
    - WORKER_CLASS=vumi.transports.telnet.TelnetServerTransport
    - VUMI_OPT_transport_name=telnet_transport
    - VUMI_OPT_telnet_port=9010
    ports:
    - "9010:9010"
    depends_on:
    - rabbitmq
  vumi-jssandbox:
    build: vxsandbox/
    volumes:
    - ./app.js:/app/app.js
    - ./app-config.json:/app/config.json
    environment:
    - AMQP_HOST=rabbitmq
    - VUMI_OPT_transport_name=telnet_transport
    depends_on:
    - rabbitmq
